'use client';

import { useEffect, useState } from 'react';
import { Signal } from '@/types';
import SignalCard from '@/components/SignalCard';

export default function SignalsPage() {
  const [signals, setSignals] = useState<Signal[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'all' | 'BUY' | 'SELL' | 'HOLD'>('all');

  useEffect(() => {
    fetch('/api/signals')
      .then(r => r.json())
      .then(data => { setSignals(data.signals || []); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const filtered = filter === 'all' ? signals : signals.filter(s => s.signal === filter);
  const buyCount = signals.filter(s => s.signal === 'BUY').length;
  const sellCount = signals.filter(s => s.signal === 'SELL').length;
  const holdCount = signals.filter(s => s.signal === 'HOLD').length;

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold mb-2">Trading Signals</h1>
        <p className="text-gray-400 text-sm">
          AI-powered signals based on RSI, price momentum, volume analysis, and trend detection.
          Updated every 2 minutes from live market data.
        </p>
      </div>

      {/* Signal Summary */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="bg-crypto-card border border-crypto-green/30 rounded-xl p-4 text-center">
          <p className="text-3xl font-bold text-crypto-green">{buyCount}</p>
          <p className="text-xs text-gray-500 uppercase mt-1">Buy Signals</p>
        </div>
        <div className="bg-crypto-card border border-crypto-yellow/30 rounded-xl p-4 text-center">
          <p className="text-3xl font-bold text-crypto-yellow">{holdCount}</p>
          <p className="text-xs text-gray-500 uppercase mt-1">Hold Signals</p>
        </div>
        <div className="bg-crypto-card border border-crypto-red/30 rounded-xl p-4 text-center">
          <p className="text-3xl font-bold text-crypto-red">{sellCount}</p>
          <p className="text-xs text-gray-500 uppercase mt-1">Sell Signals</p>
        </div>
      </div>

      {/* Filter */}
      <div className="flex gap-2 mb-6">
        {(['all', 'BUY', 'SELL', 'HOLD'] as const).map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              filter === f
                ? f === 'BUY' ? 'bg-crypto-green text-white'
                : f === 'SELL' ? 'bg-crypto-red text-white'
                : f === 'HOLD' ? 'bg-crypto-yellow text-black'
                : 'bg-crypto-accent text-white'
                : 'bg-crypto-border text-gray-400 hover:text-white'
            }`}
          >
            {f === 'all' ? 'All' : f} {f !== 'all' && `(${signals.filter(s => s.signal === f).length})`}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[...Array(6)].map((_, i) => (
            <div key={i} className="bg-crypto-card border border-crypto-border rounded-xl p-6 animate-pulse">
              <div className="h-10 bg-gray-700 rounded w-1/2 mb-4" />
              <div className="h-4 bg-gray-700 rounded w-3/4 mb-2" />
              <div className="h-4 bg-gray-700 rounded w-1/2" />
            </div>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filtered.map(signal => (
            <SignalCard key={signal.coinId} signal={signal} />
          ))}
        </div>
      )}

      {/* Disclaimer */}
      <div className="mt-8 bg-crypto-card border border-crypto-border rounded-xl p-4">
        <p className="text-xs text-gray-500">
          âš ï¸ <strong>Disclaimer:</strong> These signals are generated by algorithmic analysis of market data and are for
          educational/paper trading purposes only. They do not constitute financial advice. Always do your own research
          before making real trading decisions.
        </p>
      </div>
    </div>
  );
}
